version: '3.7'
services:
  db:
    image: mysql:5.7.12
    environment:
      MYSQL_DATABASE: 'measure'
      MYSQL_USER: 'spark'
      MYSQL_PASSWORD: 'spark'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./src/main/resources/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
