FROM localhost:5000/eschizoid/spark:python

COPY src/main/python/* /opt/spark/exmaples/iot-device/
COPY src/main/resources/libs/spark-sql-kinesis_2.11-2.4.0.jar /usr/lib/python3.6/site-packages/site-packages/pyspark/jars/spark-sql-kinesis_2.11-2.4.0.jar
